using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Chronolibris.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ChangeIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE books 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE contents 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE tags 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE book_files 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE book_fragments 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE book_participations 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE reports 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE moderation_tasks 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE bookmarks 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE shelves 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE comments 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE reviews 
                ALTER COLUMN id SET GENERATED ALWAYS;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE books 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE contents 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE tags 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE book_files 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE book_fragments 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE book_participations 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE reports 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE moderation_tasks 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE bookmarks 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE shelves 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE comments 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE reviews 
                ALTER COLUMN id SET GENERATED BY DEFAULT;
            ");
        }
    }
}
